---
title: "Plotly"
author: "Patrick Hausmann"
date: 2016-12-11T07:26:14-01:00
categories: ["R"]
---

# Interactivity in Hugo via `blogdown`

For `blogdown` see [https://github.com/rstudio/blogdown](https://github.com/rstudio/blogdown)

```{r warning=FALSE, message=FALSE}

library('ggplot2')
library('plotly')

```

```{r}

p <- plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
p

```

```{r echo = FALSE, warning=FALSE, message=FALSE}

library(quantmod)

# Download some data
getSymbols(Symbols = c("AAPL", "MSFT"))

ds <- data.frame(Date = index(AAPL), AAPL[,6], MSFT[,6])

p <- plot_ly(ds, x = ~Date) %>%
  add_lines(y = ~AAPL.Adjusted, name = "Apple") %>%
  add_lines(y = ~MSFT.Adjusted, name = "Microsoft") %>%
  layout(
    title = "Stock Prices",
    xaxis = list(
      rangeselector = list(
        buttons = list(
          list(
            count = 3,
            label = "3 mo",
            step = "month",
            stepmode = "backward"),
          list(
            count = 6,
            label = "6 mo",
            step = "month",
            stepmode = "backward"),
          list(
            count = 1,
            label = "1 yr",
            step = "year",
            stepmode = "backward"),
          list(
            count = 1,
            label = "YTD",
            step = "year",
            stepmode = "todate"),
          list(step = "all"))),

      rangeslider = list(type = "date")),

    yaxis = list(title = "Price"))

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
#chart_link = plotly_POST(p, filename="rangeslider")

p
```

